services:
  postgres:
    image: postgres:18-alpine
    container_name: hy-shop-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: hyshop
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hy-shop-network

volumes:
  postgres_data:

networks:
  hy-shop-network:
    driver: bridge
